### ISSUE TITLE
[Feature] Update `OrderForm`

### ISSUE THREAD

**Issue by zake-dev** [zake-dev/online-car-rental-system-webapp#11]
## Tasks
- [x] Add Payment type
- [x] Update layouts
- [x] Add continue selection button
- [x] Add bond amount, total price summary
- [x] Update modal message
- [x] Update api calling logic
