### ISSUE TITLE
GET bont amount based on email

### ISSUE THREAD

**Issue by zake-dev** [zake-dev/online-car-rental-system-webapp#4]
Users should pay $200 for a bond if they did not use the service in previous 3 months.

## Entities
1. `RentingHistory`
- [ ] Create `RentingHistory` entity.

## Tasks
- [ ] Search renting history in the past three months of given `email` address.
- [ ] Return bond amount $200 or $0 by using search function.
