### ISSUE TITLE
[Feature] Add repository handling `cars.json`

### ISSUE THREAD

**Issue by zake-dev** [zake-dev/online-car-rental-system-webapp#9]
## Tasks

1. Fetch from API
- [x] Fetch `cars.json` from API

2. Categories
- [x] Provide category list with its count based on refined tree:
```json
[
  {
    "category": "Sedan",
    "itemsCount": 5
  },
  ...
]
```
- [x] Filter count by 'name'

3. Cars
- [x] Filter the list by 'name', 'category'
